version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  backend:
    build:
      context: ./aethra-backend
    volumes:
      - ./aethra-backend:/app
    ports:
      - "8002:8002"  # Make sure this port is mapped
    depends_on:
      - db
    environment:
      - DEBUG=1  # Enable Django debug mode for development
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    restart: always

  aethra-frontend:
    build:
      context: ./aethra-frontend
      dockerfile: Dockerfile
    volumes:
      - ./aethra-frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  aethra-nginx:
    build:
      context: ./aethra-frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - aethra-frontend
    restart: always

volumes:
  postgres_data:
