FROM openresty/openresty:alpine

RUN apk add --no-cache nginx-mod-http-headers-more

COPY aethra-frontend/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY aethra-frontend/config/nginx/mime.types /etc/nginx/mime.types
COPY aethra-frontend/config/ssl/fullchain.pem /etc/letsencrypt/live/kairos.gr/fullchain.pem
COPY aethra-frontend/config/ssl/privkey.pem /etc/letsencrypt/live/kairos.gr/privkey.pem
COPY aethra-frontend/build /usr/share/nginx/html

EXPOSE 80 443
