FROM node:20.9-alpine

WORKDIR /app

COPY aethra-frontend/package*.json ./
RUN npm cache clean --force && npm install --legacy-peer-deps

COPY aethra-frontend/ .

RUN npm run build

CMD ["npm", "start"]
