FROM python:3.10-slim

WORKDIR /app

COPY aethra-backend/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY aethra-backend/ /app/

CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
