apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml
  - nginx/nginx-deployment.yaml
  - nginx/nginx-service.yaml
  - ingress/ingress.yaml
